#
# https://github.com/gurucomputing/headscale-ui
# https://headscale.net/stable/setup/install/container/#configure-and-run-headscale
#

services:
  headscale:
    container_name: headscale
    image: ghcr.io/juanfont/headscale:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Los_Angeles}
    volumes:
      - ${LOCVOL1}headscale/config:/etc/headscale
      - ${LOCVOL1}headscale/data:/var/lib/headscale
      #- ./container-config:/etc/headscale
      #- ./container-data/data:/var/lib/headscale
    tmpfs:
      - /var/run/headscale
    ports:
      - 8080:8080
      - 9090:9090
    command: serve
    healthcheck:
        test: ["CMD", "headscale", "health"]
    restart: unless-stopped
  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Los_Angeles}
    restart: unless-stopped
    # ports:
      # - 8443:8443
      # - 8080:8080

networks:
  default:
    name: ${CONNET}
    external: true
